version: "3.8"

services:

  app:
    restart: "unless-stopped"
    build:
      context: .
    volumes:
      - ./cache:/root/.cache
      - ./rugpt3xl.py:/app/rugpt3xl.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
